const carrerasUNNOBA = [
	"Agronomía",
	"Ingeniería Agronómica",
	"Tecnicatura en Mecanización de la Producción Agropecuaria",
	"Tecnicatura en Producción Agropecuaria",
	"Licenciatura en Ciencias de los Alimentos",
	"Ingeniería en Alimentos",
	"Tecnicatura en Producción de Alimentos",
	"Licenciatura en Genética",
	"Enfermería",
	"Licenciatura en Enfermería",
	"Contador Público",
	"Licenciatura en Administración",
	"Tecnicatura en Gestión de PYMES",
	"Tecnicatura en Gestión Pública",
	"Abogacía",
	"Martillero y Corredor Público",
	"Licenciatura en Diseño de Indumentaria y Textil",
	"Tecnicatura en Diseño de Indumentaria y Textil",
	"Licenciatura en Diseño Gráfico",
	"Tecnicatura en Diseño Gráfico",
	"Licenciatura en Diseño Industrial",
	"Tecnicatura en Diseño Industrial",
	"Ingeniería Industrial",
	"Tecnicatura en Mantenimiento Industrial",
	"Tecnicatura en Ferrocarriles",
	"Ingeniería Mecánica",
	"Tecnicatura en Mecánica",
	"Licenciatura en Sistemas",
	"Programador Universitario",
	"Analista de Sistemas",
	"Ingeniería en Informática",
	"Tecnicatura en Informática Agropecuaria",
	"Tecnicatura Universitaria en Soporte Informático",
	"Técnico Universitario en Desarrollo de Sistemas Informáticos",
];

export default carrerasUNNOBA;
